### ISSUE TITLE
Server error when updating a published score set

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb#161]
When trying to update a published score set's title and short description, I encountered the following exception:

```python
2021-09-30 17:06:43 255ae90e815d django[199] ERROR The following error occurred during ScoreSet creation:
'scoreset_form'
Traceback (most recent call last):
  File "/srv/app/dataset/views/scoreset.py", line 171, in form_valid
    self.save_forms(form)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/srv/app/dataset/views/scoreset.py", line 577, in save_forms
    forms = super().save_forms(forms=forms)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/srv/app/dataset/views/scoreset.py", line 222, in save_forms
    scoreset_form: ScoreSetForm = forms["scoreset_form"]
KeyError: 'scoreset_form'
```

**Comment by EstelleDa** [comment]
@afrubin I tried it, but it can work on my site. I edited the short title and short description together, only edited the short title, and only edited the short description of a score set. All of them showed me successfully updated.

**Comment by afrubin** [comment]
> @afrubin I tried it, but it can work on my site. I edited the short title and short description together, only edited the short title, and only edited the short description of a score set. All of them showed me successfully updated.

This works correctly for unpublished (private datasets with `tmp:` prefix), but not for the special case when the dataset has been published.
