### ISSUE TITLE
Non-ASCII character input cause Markdown parsing failure

### ISSUE THREAD

**Issue by jweile** [VariantEffect/mavedb#83]
For some (but apparently not all datasets) the Abstract and Methods are not displayed. I'm experiencing this issue currently with a prviate dataset ( tmp:uF43MjFJNzCDZ63c), where the abstract and methods contents are visible in edit mode, but are not displayed in the preview or in display mode. (See screenshots below)

![image](https://user-images.githubusercontent.com/31638122/49045143-040eb680-f19e-11e8-93d7-9f880a170e96.png)

![image](https://user-images.githubusercontent.com/31638122/49045105-e3466100-f19d-11e8-8d5a-5ef8b542f5a7.png)

This may be a problem only with private datasets, but I haven't tested that theory yet.

**Comment by jweile** [comment]
Update: I figured out that this is due to non-ASCII characters in the text. In this case an mdash and greek Delta character. I assume they caused Pandoc to fail.

**Comment by daniaki** [comment]
Would you be able to post a sample of the characters used that caused this issue? Thanks.

**Comment by afrubin** [comment]
Here's what this error generates in the server log file. Looks like we can try changing the codec to fix it maybe?

```
[ERROR] 2019-08-08 02:15:30,575 exception Internal Server Error: /profile/edit/experiment/tmp:Kh1ALpprUjFwBpdg/
Traceback (most recent call last):
  File "/data/mavedb_project/mavedb_venv/lib/python3.4/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/data/mavedb_project/mavedb_venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/mavedb_project/mavedb_venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/mavedb_project/mavedb_venv/lib/python3.4/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/mavedb_project/mavedb/dataset/views/base.py", line 185, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/data/mavedb_project/mavedb_venv/lib/python3.4/site-packages/django/contrib/auth/mixins.py", line 92, in dispatch
    return super(PermissionRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/data/mavedb_project/mavedb/dataset/views/base.py", line 70, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/data/mavedb_project/mavedb_venv/lib/python3.4/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/mavedb_project/mavedb/dataset/views/base.py", line 74, in get
    return self.get_ajax(request, *args, **kwargs)
  File "/data/mavedb_project/mavedb/dataset/mixins.py", line 259, in get_ajax
    request.GET.get("abstractText", "")
  File "/data/mavedb_project/mavedb/core/utilities/pandoc.py", line 26, in convert_md_to_html
    source, to="html", format="md", extra_args=extra_args, **kwargs
  File "/data/mavedb_project/mavedb_venv/lib/python3.4/site-packages/pypandoc/__init__.py", line 58, in convert
    path = _identify_path(source)
  File "/data/mavedb_project/mavedb_venv/lib/python3.4/site-packages/pypandoc/__init__.py", line 159, in _identify_path
    result = urlparse(source)
  File "/usr/lib64/python3.4/urllib/parse.py", line 292, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/usr/lib64/python3.4/urllib/parse.py", line 112, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/lib64/python3.4/urllib/parse.py", line 96, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/lib64/python3.4/urllib/parse.py", line 96, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 57: ordinal not in range(128)
```

**Comment by afrubin** [comment]
This is still happening. @daniaki is it possible to fix by updating a dependency?

**Comment by daniaki** [comment]
Seems like this is a python 3.4 unicode issue. Closing this since we are migrating to python 3.6 in the next update.
